[package]
name = "my-jay-config"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
jay-config = { path = "../jay/jay-config" }
log = "0.4.14"
chrono = "0.4.19"
sysinfo = "0.24.2"
